[project]
name = "pctx0"
version = "0.1.0"
description = "Python client of actx0 platform"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE"]
authors = [
    { name = "Ahmed", email = "hello@actx0.com" }
]
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
]

[project.optional-dependencies]
chunk = [
    "chonkie>=1.7.0",
]

[build-system]
requires = ["uv_build>=0.9.12,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "chonkie>=1.7.0",
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
